config/routes.rb
WebSite2::Application.routes.draw do

  root :to => 'website_controller#index'
  get '/events', :to => 'website_controller#events'
  get '/shop', :to => 'website_controller#shop'
  get '/discussion', :to => 'website_controller#discussion'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/website_controller_controller.rb
class WebsiteControllerController < ApplicationController
  def index
  	@title = "HomePage"
  end

  def events
  	@title = "Events"
  end

  def shop
  	@title = "Shop"
  end

  def discussion
  	@title = "Discussion"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		base_title = "Matteo's WebSite"

		if @title.nil?
			base_title
		else
			"#{@title}|#{base_title}"
		end
	end
end

app/helpers/website_controller_helper.rb
module WebsiteControllerHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<sub>Made by Matteo</sub>
</footer>

app/views/layouts/_header.html.erb
<header>
	<h1>Che spocchia sto sito!!</h1>
</header>

app/views/layouts/_navigation.html.erb
<nav>
	<ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Events", events_path %></li>
		<li><%= link_to "Shop", shop_path %></li>
		<li><%= link_to "Discussion", discussion_path %></li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render "layouts/navigation" %>

<%= render "layouts/header" %>

<%= yield %>

<%= render "layouts/footer" %>

</body>
</html>

app/views/website_controller/discussion.html.erb
<h1>WebsiteController#discussion</h1>
<p>Find me in app/views/website_controller/discussion.html.erb</p>

app/views/website_controller/events.html.erb
<h1>WebsiteController#events</h1>
<p>Find me in app/views/website_controller/events.html.erb</p>

app/views/website_controller/index.html.erb
<h1>WebsiteController#index</h1>
<p>Find me in app/views/website_controller/index.html.erb</p>

app/views/website_controller/shop.html.erb
<h1>WebsiteController#shop</h1>
<p>Find me in app/views/website_controller/shop.html.erb</p>